/** Declaration file generated by dts-gen */

export function assurePathExists(object: any, path: string, defaultValue: any): boolean;

export function deepEq(left: any, right: any): boolean;

export function get(object: any, path: string, defaultValue?: any): any;

export function getObjectPath(path: string): string[];

export function getStringPathForArray(arrayPath: string[]): string;

export function getTypeString(data: any): string;

export function has(object: any, key: string | string[]): boolean;

export function hasRoot(object: any, key: string | string[]): boolean;

export function keys(object: any): string[];

export function set(object: any, path: string, value: any): any;
